name: WhereIsPlugin
version: @version@
main: xyz.n7mn.dev.whereisplugin.WhereIsPlugin
softdepend: [LuckPerms,dynmap]
api-version: 1.15
authors: [n3m_]
description: Where am I?
website: https://n7mn.xyz/
commands:
  where:
    description: Where is ...?
    usage: /where